function normalizeProbability(value) {
  if (typeof value !== 'number' || Number.isNaN(value)) return 0;
  return Math.max(0, Math.min(100, Math.round(value)));
}

function inferTypeFromUrl(rawUrl) {
  try {
    const parsed = new URL(rawUrl);
    const path = `${parsed.pathname || ''}`.toLowerCase();
    const query = `${parsed.search || ''}`.toLowerCase();

    if (/\.(mp4|webm|mov|m4v)(\?|$)/i.test(path) || /format=(mp4|webm|mov|m4v)/i.test(query)) {
      return 'video';
    }

    if (/\.(jpg|jpeg|png|gif|webp|bmp|svg)(\?|$)/i.test(path) || /format=(jpg|jpeg|png|gif|webp|bmp|svg)/i.test(query)) {
      return 'image';
    }
  } catch (error) {
    return null;
  }

  return null;
}

function scoreUrlSignals(rawUrl, type) {
  let score = 0;
  const reasons = [];

  try {
    const parsed = new URL(rawUrl);
    const hostname = parsed.hostname.toLowerCase();
    const pathname = parsed.pathname.toLowerCase();
    const query = parsed.search.toLowerCase();
    const combined = `${hostname} ${pathname} ${query}`;

    const generatorKeywords = [
      'midjourney',
      'stable-diffusion',
      'stablediffusion',
      'dall-e',
      'dalle',
      'openai',
      'leonardo',
      'runway',
      'sora',
      'pika',
      'synthesia',
      'deepfake',
      'ai-generated',
      'generated-by-ai',
      'genai',
    ];

    const c2paKeywords = ['c2pa', 'contentcredentials', 'content-credentials'];
    const likelyNaturalKeywords = ['camera', 'dsc_', 'img_', 'gopro', 'iphone', 'samsung'];

    generatorKeywords.forEach((keyword) => {
      if (combined.includes(keyword)) {
        score += 18;
        reasons.push(`Detected AI-related source signal: ${keyword}`);
      }
    });

    c2paKeywords.forEach((keyword) => {
      if (combined.includes(keyword)) {
        score += 8;
        reasons.push(`Detected provenance marker reference: ${keyword}`);
      }
    });

    likelyNaturalKeywords.forEach((keyword) => {
      if (combined.includes(keyword)) {
        score -= 10;
        reasons.push(`Detected camera-like filename signal: ${keyword}`);
      }
    });

    if (type === 'video' && /\b(face\-swap|lip\-sync|avatar)\b/i.test(combined)) {
      score += 25;
      reasons.push('Video URL contains synthetic avatar/deepfake indicators');
    }
  } catch (error) {
    // Ignore malformed URL parsing for signal extraction.
  }

  return {
    probability: normalizeProbability(score),
    reasons,
  };
}

function scoreTextSignals(text = '') {
  if (!text) {
    return { probability: 0, reasons: [] };
  }

  const normalized = text.toLowerCase();
  let score = 0;
  const reasons = [];

  const mentions = [
    'ai-generated',
    'generated by ai',
    'synthetic media',
    'deepfake',
    'midjourney',
    'stable diffusion',
    'dall-e',
    'sora',
  ];

  mentions.forEach((term) => {
    if (normalized.includes(term)) {
      score += 14;
      reasons.push(`Content mentions synthetic-media term: ${term}`);
    }
  });

  return {
    probability: normalizeProbability(score),
    reasons,
  };
}

function summarize(probability) {
  if (probability >= 70) return 'high';
  if (probability >= 40) return 'medium';
  return 'low';
}

async function detectAIGeneratedContent({ sourceUrl, content, aiTextProbability = 0 }) {
  const images = Array.isArray(content?.images) ? content.images : [];
  const videos = Array.isArray(content?.videos) ? content.videos : [];
  const text = content?.text || '';

  const directType = inferTypeFromUrl(sourceUrl || '');
  const imageTargets = [...images];
  const videoTargets = [...videos];

  if (directType === 'image' && sourceUrl) imageTargets.push(sourceUrl);
  if (directType === 'video' && sourceUrl) videoTargets.push(sourceUrl);

  const uniqueImages = Array.from(new Set(imageTargets.filter(Boolean)));
  const uniqueVideos = Array.from(new Set(videoTargets.filter(Boolean)));

  const imageEvidence = uniqueImages.slice(0, 5).map((url) => {
    const result = scoreUrlSignals(url, 'image');
    return {
      url,
      probability: result.probability,
      reasons: result.reasons,
    };
  });

  const videoEvidence = uniqueVideos.slice(0, 5).map((url) => {
    const result = scoreUrlSignals(url, 'video');
    return {
      url,
      probability: result.probability,
      reasons: result.reasons,
    };
  });

  const textSignal = scoreTextSignals(text);

  const imageProbability = imageEvidence.length
    ? Math.max(...imageEvidence.map((item) => item.probability))
    : 0;
  const videoProbability = videoEvidence.length
    ? Math.max(...videoEvidence.map((item) => item.probability))
    : 0;
  const textProbability = normalizeProbability(Math.max(aiTextProbability, textSignal.probability));

  const overallProbability = normalizeProbability(
    Math.max(textProbability, imageProbability, videoProbability)
  );

  return {
    overall_probability: overallProbability,
    overall_level: summarize(overallProbability),
    likely_ai_generated: overallProbability >= 55,
    text: {
      probability: textProbability,
      level: summarize(textProbability),
      reasons: textSignal.reasons,
    },
    image: {
      probability: imageProbability,
      level: summarize(imageProbability),
      analyzed_count: imageEvidence.length,
      evidence: imageEvidence,
    },
    video: {
      probability: videoProbability,
      level: summarize(videoProbability),
      analyzed_count: videoEvidence.length,
      evidence: videoEvidence,
    },
  };
}

module.exports = {
  detectAIGeneratedContent,
};
